# Generated by Django 5.0.2 on 2024-06-18 13:55

import recipes.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeingredient',
            name='unit',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[recipes.validators.validate_unit_of_measure]),
        ),
    ]
